export interface MenuItem {
  id: string;
  name: string;
  category: 'portraits' | 'glamour' | 'gentleman' | 'vintage' | 'trips' | 'street' | 'birthdays' | 'lifestyle';
  price: string;
  notes: string[];
  image: string;
  origin: string;
  description: string;
}

export const MENU_CATEGORIES = [
  { id: 'all', label: 'All Memories' },
  { id: 'portraits', label: 'Aesthetic Portraits' },
  { id: 'glamour', label: 'Glamour & Fashion' },
  { id: 'gentleman', label: "Gentleman's Style" },
  { id: 'vintage', label: 'Vintage & Film' },
  { id: 'trips', label: 'Trips & Outdoors' },
  { id: 'street', label: 'Urban Street' },
  { id: 'birthdays', label: 'Birthdays & Parties' },
  { id: 'lifestyle', label: 'Executive Lifestyle' },
] as const;

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'wet-sand-beach',
    name: 'Serene Wet Sand Beach Memory',
    category: 'trips',
    price: 'Beach Trip',
    origin: 'Modelix AI Studio',
    notes: ['Coastal Tide', 'Natural Sunset', '8K Resolution'],
    description: 'Hyper-realistic AI travel photoshoot capturing peaceful moments on wet ocean sand.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264890/Woman_sitting_on_wet_sand_202608091404_lmrjfm.jpg',
  },
  {
    id: 'beach-sunset-walk',
    name: 'Coastal Sunset Beach Walk',
    category: 'trips',
    price: 'Coastal Journey',
    origin: 'Modelix AI Studio',
    notes: ['Ocean Horizon', 'Golden Sunset', 'Cinematic Tone'],
    description: 'Photorealistic beach walk photoshoot synthesized with warm coastal sunset lighting.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264899/Woman_walking_on_beach_2K_202608091405_lnc8gw.jpg',
  },
  {
    id: 'joyful-floral-celebration',
    name: 'Joyful Floral Celebration',
    category: 'birthdays',
    price: 'Milestone Party',
    origin: 'Modelix AI Studio',
    notes: ['Candid Laughter', 'Floral Detail', 'Vibrant Light'],
    description: 'Vibrant celebration portrait capturing candid laughter and floral aesthetic.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264911/Woman_laughing_adjusting_flower_2K_202608091358_chamq6.jpg',
  },
  {
    id: 'sunset-rowboat-serenade',
    name: 'Sunset Rowboat Serenade',
    category: 'trips',
    price: 'Sunset Journey',
    origin: 'Modelix AI Studio',
    notes: ['Lake Reflection', 'Golden Dusk', '8K Detail'],
    description: 'Cinematic sunset rowboat photoshoot created with golden water reflections.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264911/Woman_in_rowboat_at_sunset_202608091402_3_o6ii3f.jpg',
  },
  {
    id: 'ethereal-sunset-glow',
    name: 'Ethereal Sunset Glow',
    category: 'portraits',
    price: 'Aesthetic Portrait',
    origin: 'Modelix AI Studio',
    notes: ['Dreamy Backlight', 'Soft Glow', 'Studio Lighting'],
    description: 'High-definition dreamlike sunset portrait with luminous backlight.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264915/need_improive_this_image_2K_202608091407_pdpmt7.jpg',
  },
  {
    id: 'golden-sunbeam-portrait',
    name: 'Golden Sunbeam Portrait',
    category: 'portraits',
    price: 'Sunbeam Glow',
    origin: 'Modelix AI Studio',
    notes: ['Sunbeam Flare', 'Natural Sun', 'Ultra Sharp'],
    description: 'Soft sunbeam aesthetic portrait designed for personal milestone memories.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264917/need_improive_this_image_2K_202608091407_1_j5g8zl.jpg',
  },
  {
    id: 'blossom-crown-celebration',
    name: 'Blossom Crown Celebration',
    category: 'birthdays',
    price: 'Birthday Shoot',
    origin: 'Modelix AI Studio',
    notes: ['Flower Crown', 'Milestone Party', 'Celebration Vibe'],
    description: 'Intimate milestone portrait with fresh flower crown and candid laughter.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264919/Woman_laughing_adjusting_flower_2K_202608091358_1_hqmiml.jpg',
  },
  {
    id: 'ocean-tide-reflection',
    name: 'Ocean Tide Reflection',
    category: 'trips',
    price: 'Tide Memory',
    origin: 'Modelix AI Studio',
    notes: ['Coastal Breeze', 'Wet Sand', 'Serene Water'],
    description: 'Tranquil coastal photoshoot capturing gentle tide reflections and sea breeze.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264920/Woman_sitting_on_wet_sand_202608091405_od08cv.jpg',
  },
  {
    id: 'golden-hour-glance',
    name: 'Golden Hour Glance',
    category: 'glamour',
    price: 'Glamour Shoot',
    origin: 'Modelix AI Studio',
    notes: ['Golden Hour', 'Glamour Glance', '8K Skin Texture'],
    description: 'Photorealistic over-the-shoulder portrait with soft golden hour lighting.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264929/Blonde_woman_looking_over_shoulder_202608091357_vtecqp.jpg',
  },
  {
    id: 'summer-grass-picnic',
    name: 'Summer Grass Picnic',
    category: 'trips',
    price: 'Nature Trip',
    origin: 'Modelix AI Studio',
    notes: ['Lush Grass', 'Outdoor Sun', 'Nature Vibe'],
    description: 'Peaceful outdoor nature photoshoot synthesized in lush summer grass.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264937/Woman_sitting_in_grass_2K_202608091357_vri56f.jpg',
  },
  {
    id: 'twilight-lake-rowboat',
    name: 'Twilight Lake Rowboat',
    category: 'trips',
    price: 'Lake Voyage',
    origin: 'Modelix AI Studio',
    notes: ['Twilight Sky', 'Calm Water', 'Romantic Voyage'],
    description: 'Romantic lake voyage photoshoot set against glowing twilight horizons.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264940/Woman_in_rowboat_at_sunset_202608091402_1_d0swby.jpg',
  },
  {
    id: 'wildflower-bouquet-memory',
    name: 'Wildflower Bouquet Memory',
    category: 'vintage',
    price: 'Vintage Memory',
    origin: 'Modelix AI Studio',
    notes: ['Wildflowers', 'Soft Film Grain', 'Analog Vibe'],
    description: 'Aesthetic vintage portrait holding a fresh wildflower bouquet with film grain.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264942/Young_woman_looking_at_bouquet_202608091355_gj6aoz.jpg',
  },
  {
    id: 'meadow-breeze-portrait',
    name: 'Meadow Breeze Portrait',
    category: 'vintage',
    price: 'Meadow Memory',
    origin: 'Modelix AI Studio',
    notes: ['Natural Sunbeam', 'Meadow Flora', 'Nostalgic Tone'],
    description: 'Timeless meadow photoshoot captured in soft natural sunbeams.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264945/Woman_in_meadow_holding_weeds_202608091355_1_bjpp0n.jpg',
  },
  {
    id: 'sunlit-grass-serenity',
    name: 'Sunlit Grass Serenity',
    category: 'portraits',
    price: 'Personal Portrait',
    origin: 'Modelix AI Studio',
    notes: ['Lawn Serenity', 'Soft Light', '8K Detail'],
    description: 'Serene aesthetic portrait lying in sunlit grass with 8K fidelity.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264949/Young_woman_lying_in_grass_202608091355_m8cavf.jpg',
  },
  {
    id: 'forest-canopy-portrait',
    name: 'Forest Canopy Portrait',
    category: 'street',
    price: 'Forest Walk',
    origin: 'Modelix AI Studio',
    notes: ['Mossy Woodland', 'Forest Shade', 'Cinematic Tone'],
    description: 'Cinematic forest portrait leaning against mossy woodland trees.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264958/Woman_leaning_against_tree_2K_202608091401_tqzezn.jpg',
  },
  {
    id: 'emerald-lawn-reverie',
    name: 'Emerald Lawn Reverie',
    category: 'portraits',
    price: 'Aesthetic Portrait',
    origin: 'Modelix AI Studio',
    notes: ['Emerald Lawn', 'Dreamy Vibe', 'Natural Lighting'],
    description: 'Dreamy outdoor aesthetic portrait captured on an emerald green lawn.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264961/Woman_lying_in_grass_2K_202608091355_jjuuch.jpg',
  },
  {
    id: 'golden-lake-sunset-voyage',
    name: 'Golden Lake Sunset Voyage',
    category: 'trips',
    price: 'Lake Voyage',
    origin: 'Modelix AI Studio',
    notes: ['Sunset Voyage', 'Golden Water', 'Romantic Vibe'],
    description: 'Breathtaking sunset lake photoshoot featuring golden water reflections.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264962/Woman_in_rowboat_at_sunset_202608091402_rliebf.jpg',
  },
  {
    id: 'dusk-river-reflection',
    name: 'Dusk River Reflection',
    category: 'trips',
    price: 'River Memory',
    origin: 'Modelix AI Studio',
    notes: ['Dusk Sky', 'River Water', 'Quiet Serenity'],
    description: 'Tranquil dusk river photoshoot surrounded by glowing sunset horizon.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264971/Woman_in_rowboat_at_sunset_202608091402_2_kj1sob.jpg',
  },
  {
    id: 'soft-elegance-portrait',
    name: 'Soft Elegance Portrait',
    category: 'glamour',
    price: 'Glamour Shoot',
    origin: 'Modelix AI Studio',
    notes: ['Soft Shadows', 'Glance Back', 'Chic Elegance'],
    description: 'Elegant portrait shoot with soft studio lighting and over-the-shoulder glance.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264976/Woman_looking_over_shoulder_2K_202608091401_xacfsz.jpg',
  },
  {
    id: 'golden-meadow-harvest',
    name: 'Golden Meadow Harvest',
    category: 'vintage',
    price: 'Vintage Memory',
    origin: 'Modelix AI Studio',
    notes: ['Analog Film Grain', 'Golden Meadow', 'Warm Glow'],
    description: 'Nostalgic golden meadow portrait rendered with soft analog film grain.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264983/Woman_in_meadow_holding_weeds_202608091355_e5ddwp.jpg',
  },
  {
    id: 'scenic-pathway-walk',
    name: 'Scenic Pathway Walk',
    category: 'street',
    price: 'Pathway Walk',
    origin: 'Modelix AI Studio',
    notes: ['Motion Walk', 'Dappled Sunlight', 'Pathway Vibe'],
    description: 'Dynamic motion portrait walking along a sun-dappled scenic pathway.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264988/Woman_walking_towards_camera_2K_202608091400_udjz22.jpg',
  },
  {
    id: 'riverbank-silk-harmony',
    name: 'Riverbank Silk Harmony',
    category: 'trips',
    price: 'River Trip',
    origin: 'Modelix AI Studio',
    notes: ['Riverbank', 'Flowing Dress', 'Natural Sunlight'],
    description: 'Elegant riverbank photoshoot with flowing dress and serene water backdrop.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264997/Woman_sitting_on_riverbank_dress_202608091401_aujel8.jpg',
  },
  {
    id: 'luminous-sunlit-glow',
    name: 'Luminous Sunlit Glow',
    category: 'portraits',
    price: 'Sunlit Portrait',
    origin: 'Modelix AI Studio',
    notes: ['Crystalline Flare', '8K Resolution', 'Sunlight Vibe'],
    description: 'Hyper-realistic sunlit portrait synthesized with crystalline clarity.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786264999/need_improive_this_image_2K_202608091354_1_sahhag.jpg',
  },
  {
    id: 'studio-chic-elegance',
    name: 'Studio Chic Elegance',
    category: 'glamour',
    price: 'Studio Chic',
    origin: 'Modelix AI Studio',
    notes: ['Sleek Glamour', 'Studio Light', 'Chic Finish'],
    description: 'Sleek studio glamour photoshoot tailored for personal aesthetic profiles.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265004/give_me_it_this_size_202608091344_qjyga1.jpg',
  },
  {
    id: 'cinematic-warmth-portrait',
    name: 'Cinematic Warmth Portrait',
    category: 'portraits',
    price: 'Warm Portrait',
    origin: 'Modelix AI Studio',
    notes: ['Cinematic Tone', 'Soft Shadow', 'Timeless Memory'],
    description: 'Warm cinematic studio portrait designed for timeless memory keepsake.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265008/need_improive_this_image_2K_202608091354_z159cv.jpg',
  },
  {
    id: 'peach-blossom-dress',
    name: 'Peach Blossom Dress Shoot',
    category: 'birthdays',
    price: 'Celebration Dress',
    origin: 'Modelix AI Studio',
    notes: ['Peach Pink Dress', 'Celebration Vibe', 'Vibrant Light'],
    description: 'Vibrant celebration photoshoot featuring a stunning peach-pink dress.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265022/Woman_in_peach-pink_dress_2K_202608091400_n4j62j.jpg',
  },
  {
    id: 'flora-crown-majesty',
    name: 'Flora Crown Majesty',
    category: 'birthdays',
    price: 'Birthday Shoot',
    origin: 'Modelix AI Studio',
    notes: ['Floral Crown', 'Milestone Party', 'Regal Vibe'],
    description: 'Enchanting birthday photoshoot with a handcrafted floral crown.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265023/Woman_wearing_floral_crown_dress_202608091343_hoknyh.jpg',
  },
  {
    id: 'velvet-dusk-glint',
    name: 'Velvet Dusk Glint',
    category: 'glamour',
    price: 'Dusk Glamour',
    origin: 'Modelix AI Studio',
    notes: ['Dusk Ambient', 'Over Shoulder', 'Soft Focus'],
    description: 'Captivating dusk glamour portrait with soft ambient lighting.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265027/Woman_looking_over_shoulder_2K_202608091400_obyzyf.jpg',
  },
  {
    id: 'crimson-rose-mystery',
    name: 'Crimson Rose Mystery',
    category: 'portraits',
    price: 'Rose Portrait',
    origin: 'Modelix AI Studio',
    notes: ['Red Rose Close-Up', 'Poetic Tone', '8K Skin Texture'],
    description: 'Poetic aesthetic portrait featuring a crimson rose close-up.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265030/Woman_face_behind_red_rose_202608091343_rhze2y.jpg',
  },
  {
    id: 'enchanted-forest-stroll',
    name: 'Enchanted Forest Stroll',
    category: 'trips',
    price: 'Forest Journey',
    origin: 'Modelix AI Studio',
    notes: ['Forest Walk', 'Sunlight Rays', 'Enchanted Nature'],
    description: 'Enchanting forest stroll photoshoot glancing back in warm sunlight.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265036/Woman_walking_glances_back_2K_202608091359_hwajvz.jpg',
  },
  {
    id: 'mossy-tree-sanctuary',
    name: 'Mossy Tree Sanctuary',
    category: 'trips',
    price: 'Nature Voyage',
    origin: 'Modelix AI Studio',
    notes: ['Ancient Tree', 'Moss Canopy', 'High Impact'],
    description: 'High-impact nature photoshoot perched on an ancient mossy tree branch.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265048/Woman_on_mossy_tree_branch_202608091341_m1sq6d.jpg',
  },
  {
    id: 'golden-sun-flare',
    name: 'Golden Sun Flare Portrait',
    category: 'portraits',
    price: 'Sun Flare Glow',
    origin: 'Modelix AI Studio',
    notes: ['Sun Flare', 'Radiant Warmth', '8K Detail'],
    description: 'Radiant portrait shoot synthesized with natural golden sun flare.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265070/need_improive_this_image_2K_202608091407_4_cerchj.jpg',
  },
  {
    id: 'sunlit-woodland-walk',
    name: 'Sunlit Woodland Walk',
    category: 'street',
    price: 'Woodland Trip',
    origin: 'Modelix AI Studio',
    notes: ['Woodland Path', 'Candid Glance', 'Sun Dappled'],
    description: 'Atmospheric woodland walk photoshoot capturing candid motion.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265072/Woman_walking_glances_back_2K_202608091358_uu4bqh.jpg',
  },
  {
    id: 'velvet-light-glow',
    name: 'Velvet Light Glow',
    category: 'portraits',
    price: 'Velvet Light',
    origin: 'Modelix AI Studio',
    notes: ['Soft Velvet Focus', 'Warm Light', 'Aesthetic Vibe'],
    description: 'Soft velvet light aesthetic portrait tailored for memory keepsakes.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265077/need_improive_this_image_2K_202608091407_2_swv7vo.jpg',
  },
  {
    id: 'botanical-haven',
    name: 'Botanical Haven Portrait',
    category: 'vintage',
    price: 'Botanical Vibe',
    origin: 'Modelix AI Studio',
    notes: ['Lush Flora', 'Botanical Garden', 'Soft Analog'],
    description: 'Lush botanical photoshoot surrounded by natural flora and soft light.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265082/give_me_this_in_this_202608091338_q4x0vl.jpg',
  },
  {
    id: 'smiling-floral-royalty',
    name: 'Smiling Floral Royalty',
    category: 'birthdays',
    price: 'Birthday Milestone',
    origin: 'Modelix AI Studio',
    notes: ['Floral Crown', 'Joyful Smile', 'Milestone Party'],
    description: 'Joyful birthday photoshoot featuring a smiling floral crown portrait.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265082/Woman_wearing_floral_crown_smiling_202608091358_nx8dzg.jpg',
  },
  {
    id: 'radiant-sunlight-harmony',
    name: 'Radiant Sunlight Harmony',
    category: 'portraits',
    price: 'Radiant Glow',
    origin: 'Modelix AI Studio',
    notes: ['Lens Flare', 'Outdoor Harmony', '8K Clarity'],
    description: 'Radiant outdoor aesthetic portrait with soft lens flare and 8K clarity.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265083/need_improive_this_image_2K_202608091407_3_cioki2.jpg',
  },
  {
    id: 'cinematic-sunset-serenity',
    name: 'Cinematic Sunset Serenity',
    category: 'trips',
    price: 'Sunset Serenity',
    origin: 'Modelix AI Studio',
    notes: ['Sunset Serenity', 'Coastal Breeze', '8K Horizon'],
    description: 'Breathtaking sunset photoshoot capturing tranquil coastal atmosphere.',
    image: 'https://res.cloudinary.com/dpx6w78bt/image/upload/f_auto,q_auto/v1786265131/need_improive_this_image_2K_202608091403_mazqug.jpg',
  },
];
